trigger:
- master

pool:
  name: project-cicd-pool
  vmImage: Az-runner

steps:

- task: Bash@3
  displayName: "Gather artifact version"
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=version]$(grep version pom.xml | grep -v ''<?xml'' | grep ''<version>''|head -n 1|awk ''{print $1}''| cut -d''>'' -f 2 | cut -d''<'' -f 1)"'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(version)'

- task: Bash@3
  displayName: "build artifacts"
  inputs:
    targetType: 'inline'
    script: |
      mvn clean package
    failOnStderr: true

- task: Bash@3
  displayName: "prepare artifact folder structure"
  inputs:
    targetType: 'inline'
    script: |
      mkdir /tmp/$(version)
      cp ./target/*.jar /tmp/$(version)/app.jar
      ls -lrt /tmp/$(version)
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '/tmp/$(version)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '13e91627-f971-47ff-8b01-9abae0997d6c/c23ee893-283e-4303-83c9-2d49487c4fcc'
    vstsFeedPackagePublish: 'javaapp'
    versionOption: 'patch'
    packagePublishDescription: '$(version)'

